apiVersion: v1
kind: ServiceAccount
metadata:
  name: tron-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tron-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tron-admin
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: tron-admin-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: tron-admin
type: kubernetes.io/service-account-token
